### ISSUE TITLE
Moving to Hugo

### ISSUE THREAD

**Issue by gsomix** [gsomix/blog#6]
OK, I decided to move my blog to [Hugo](https://gohugo.io/). It's [online right now](https://gsomix.github.io/blog/). Could anyone check if RSS feed works correctly, please? Thank you in advance!

cc @Minoru @ForNeVeR

**Comment by Minoru** [comment]
I'm happy to report that the RSS feed migrated perfectly: the old articles have the same IDs, so on my end it looks like you simply posted a new article. Great job, @gsomix! ;)

**Comment by gsomix** [comment]
OK, thank you, guys!
